libraryPath: ./music
downloadPath: ./downloads
demo: false
telegram:
  enabled: true
  token: you_can_use_TELEGRAM_TOKEN_var_instead
  allowedUsers: []
logger:
  enabled: true
  level: debug
  format: text
  htmx_debug: false
downloaders:
  plugins: []
  artwork:
    embedded:
      enabled: true
      size: 1000
      format: jpeg
      quality: 85
    local:
      enabled: false
      size: 1200
      format: jpeg
      template: cover.jpg
server:
  show_routes: false
  port: 3535
database:
  path: ./library.db
import:
  move: false
  always_queue: false
  duplicates: queue
  paths:
    compilations: '%asciify{$albumartist}/%asciify{$album} (%if{$original_year,$original_year,$year})/%asciify{$track $title}'
    album:soundtrack: '%asciify{$albumartist}/%asciify{$album} [OST] (%if{$original_year,$original_year,$year})/%asciify{$track $title}'
    album:single: '%asciify{$albumartist}/%asciify{$album} [Single] (%if{$original_year,$original_year,$year})/%asciify{$track $title}'
    album:ep: '%asciify{$albumartist}/%asciify{$album} [EP] (%if{$original_year,$original_year,$year})/%asciify{$track $title}'
    default_path: '%asciify{$albumartist}/%asciify{$album} (%if{$original_year,$original_year,$year})/%asciify{$track $title}'
tag:
  enabled: false
  providers:
    discogs:
      enabled: true
      api_key: ""
    musicbrainz:
      enabled: true
      api_key: ""
sync:
  enabled: true
  devices: []
jobs:
  log: true
  log_path: ./logs/jobs
  webhooks:
    enabled: true
    job_types:
      - directory_import
      - download_album
      - dap_sync
    command: "TEXT=\"\U0001F3B5 Job {{.Name}} ({{.Type}}) {{.Status}}\\n\U0001F4DD {{.Message}}\\n⏱️ Duration: {{.Duration}}\"\ncurl -X POST -H 'Content-Type: application/json' \\\n  -d '{\"chat_id\": \"<chat_id>\", \"text\": \"'\"$TEXT\"'\", \"parse_mode\": \"HTML\"}' \\\n  https://api.telegram.org/bot<bot_token>/sendMessage\n"
